### ISSUE TITLE
demo

### ISSUE THREAD

**Issue by shawnxu1318** [shawnxu1318/Google-Neural-Machine-Translation-GNMT-#1]
![demo](https://cloud.githubusercontent.com/assets/10870023/21465785/ef85ceb8-c965-11e6-9e02-3903fc8cc898.gif)

**Comment by shawnxu1318** [comment]
![model](https://cloud.githubusercontent.com/assets/10870023/21465786/f6f80422-c965-11e6-9b9e-609a5f87fb03.png)

**Comment by shawnxu1318** [comment]
Hi Bright, thank you for your comment! I will check that during the weekend. Also, let me know if you are interested in working on this GNMT project together. 👍

**Comment by brightmart** [comment]
Hi ShawnXu,


I'd like to work together if possible.


currently i am working on spoken diaglogue generation, and many techs used in GNMT is also applicable to the area.


Bright


________________________________
发件人: shawnxu1318 <notifications@github.com>
发送时间: 2017年2月15日 12:46
收件人: shawnxu1318/Google-Neural-Machine-Translation-GNMT-
抄送: brightmart; Comment
主题: Re: [shawnxu1318/Google-Neural-Machine-Translation-GNMT-] demo (#1)


Hi Bright, thank you for your comment! I will check that during the weekend. Also, let me know if you are interested in working on this GNMT project together. 👍

**Comment by brightmart** [comment]
Hi,


In the method of embedding_attention_seq2seq, i divide embedding_size with 2, then it can works.



    # Encoder.
    # bi-direction rnn #####################################################################################################################
    with tf.device('/gpu:0'):
        single_cell_1 = rnn_cell.LSTMCell(embedding_size/2)
    with tf.device('/gpu:1'):
        single_cell_2 = rnn_cell.LSTMCell(embedding_size/2)

    encoder_fw_cell = rnn_cell.EmbeddingWrapper(single_cell_1, embedding_classes=num_encoder_symbols, #forward cell
                                                embedding_size=embedding_size/2) #embedding_size=embedding_size
    encoder_bw_cell = rnn_cell.EmbeddingWrapper(single_cell_2, embedding_classes=num_encoder_symbols, #backward cell
                                                embedding_size=embedding_size/2) #embedding_size=embedding_size
    outputs, _, _ = rnn.bidirectional_rnn(encoder_fw_cell, encoder_bw_cell, encoder_inputs, dtype=dtype) #bi directional rnn
    #print("embedding_attention_seq2seq.*****************outputs:",outputs)
    # bi-direction rnn #####################################################################################################################


Bright
________________________________
发件人: 徐 亮 <brightmart@hotmail.com>
发送时间: 2017年2月15日 14:55
收件人: shawnxu1318/Google-Neural-Machine-Translation-GNMT-
主题: 答复: [shawnxu1318/Google-Neural-Machine-Translation-GNMT-] demo (#1)


Hi ShawnXu,


I'd like to work together if possible.


currently i am working on spoken diaglogue generation, and many techs used in GNMT is also applicable to the area.


Bright


________________________________
发件人: shawnxu1318 <notifications@github.com>
发送时间: 2017年2月15日 12:46
收件人: shawnxu1318/Google-Neural-Machine-Translation-GNMT-
抄送: brightmart; Comment
主题: Re: [shawnxu1318/Google-Neural-Machine-Translation-GNMT-] demo (#1)


Hi Bright, thank you for your comment! I will check that during the weekend. Also, let me know if you are interested in working on this GNMT project together. 👍

**Comment by shawnxu1318** [comment]
Cool！Do you want to implement the subword part?

**Comment by brightmart** [comment]
i'd like to have a try if possible. what is the expected complete date?

**Comment by shawnxu1318** [comment]
How much time do you have for next couple weeks? I am actually building my new desktop with more GPUs installed. And I will reimplement and test the multi-GPUs part soon.

**Comment by shawnxu1318** [comment]
I remember there is a Matlab version implemented by the original author already in Github. We can discuss more after you read it. 👍

**Comment by brightmart** [comment]
i will read it, and will have some time after next week. next week may busy.

**Comment by shawnxu1318** [comment]
awesome！
