### ISSUE TITLE
Code seems not working (Fixed)

### ISSUE THREAD

**Issue by TriGNguyen** [shawnxu1318/Google-Neural-Machine-Translation-GNMT-#2]
Hi Shawn,

-(similar to previous comment) "from tensorflow.models.rnn.translate import seq2seq_model" in __init__.py. should it be "import seq2seq_model"?
-Which version of your tf? I ran on tf 0.12.1 and receive many matrix size errors and float/int mismatch error.

Thanks,

**Comment by shawnxu1318** [comment]
fixed. 0.11.0rc0
